baseURL = "https://oszkar-photos.netlify.com/"
languageCode = "en-us"
title = "Oszkar photo gallery"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "photos_m"
    name = "Photo gallery 1(masonry)"
    url = "/photos_m/"
  [[menu.main]]
    identifier = "photos_s"
    name = "Photo gallery 2(square)"
    url = "/photos_s/"
